tag:
  - math_word_problems
task: aime25_nofigures_retrieval_agg4
dataset_path: MathArena/aime_2025
dataset_name: default
process_docs: !function utils.process_docs_aime25_with_retrieval
output_type: generate_until
test_split: train
doc_to_text: !function utils.doc_to_text_with_retrieval
doc_to_target: answer
process_results: !function utils.process_results
generation_kwargs:
  until: []
  do_sample: false
  temperature: 1
  max_gen_toks: 65536
repeats: 4
filter_list:
  - name: "all" # Will do coverage, majority, and take_first_k
    filter:
      - function: "take_first_k"
        k: 4
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
  - metric: cov@4
    aggregation: mean
    higher_is_better: true
  - metric: cov@2
    aggregation: mean
    higher_is_better: true
  - metric: maj@4
    aggregation: mean
    higher_is_better: true
  - metric: maj@2
    aggregation: mean
    higher_is_better: true
  - metric: extracted_answers
    aggregation: bypass
    higher_is_better: true
  - metric: exact_matches
    aggregation: bypass
    higher_is_better: true
metadata:
  version: 1.0
